# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='In Process', max_length=10)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orNum', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('isApproved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('idNum', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('cpNum', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=3)),
                ('degree', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=1)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='idNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbhandler.Student'),
        ),
        migrations.AddField(
            model_name='loan',
            name='idNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbhandler.Student'),
        ),
    ]
