# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 05:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=8)),
                ('college', models.CharField(blank=True, max_length=10)),
                ('course', models.CharField(blank=True, max_length=10)),
                ('cellphone_number', models.CharField(blank=True, max_length=11)),
                ('payment', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
