# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=8)),
                ('college', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=10)),
                ('cellphone_number', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('payment', models.FloatField(default=0.0)),
            ],
        ),
    ]
